remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Bangladeshi Snake indentifier
description: An image classification API that classifies 17 different types of snake found in Bangladesh and southestern Asia

author:
  name: Md. Shakhawat Hossain


# remote_theme: daviddarnes/alembic@main
# plugins:
#   - jekyll-remote-theme

# title: Bangladeshi Snake Identifier
# description: An image classification API that classifies 17 different types of snakes found in Bangladesh and southeastern Asia

# author:
#   name: Md. Shakhawat Hossain

# # Optional customization
# logo: /assets/images/logo.png  # if you want a logo
# social_links:
#   - name: GitHub
#     url: https://github.com/Rafix007
#   - name: LinkedIn
#     url: https://www.linkedin.com/in/shakhawat-hossain/

# # Optional footer
# footer: "© 2025 Md. Shakhawat Hossain. All rights reserved."
