# Use a remote Jekyll theme
remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme

# Site settings
title: Bangladeshi Snake Recognizer
description: An image classification tool that identifies 17 types of snakes found in Bangladesh and Southeast Asia.

author:
  name: Md. Shakhawat Hossain
  email: shakhawat43000@gmail.com